added param typing to walk function and updated the walk function to take in num_steps as a list
nateraw/stable-diffusion-videos pull request #52
Opened 2022-09-21 14:50 UTC by danielpatrickhug

Hello, @nateraw 
issue reference: #41 
- this pull request changes the function parameter num_steps from an int to a list. 
- the code has been tested on colab as my local computer does not have a gpu
- tested w/ bools, resume, do_loop, and passing in an int instead of a list for num_steps.

2022-09-21 15:39 UTC, nateraw requested changes
Looks good! Thanks for your contribution ❤️

I would suggest leaving the `int` type for num steps so we have backwards compatibility. type as `Union[int, List[int]]`. Leave default as `5` (I don't like list defaults, they can do wonky things in Python).

2022-09-21 15:39 UTC, nateraw commented on stable_diffusion_videos/stable_diffusion_walk.py
> +    num_steps:list=[5],
Leave default here as int. type it as `Union[int, List[int]]`.

2022-09-21 17:00 UTC, nateraw reviewed
Some minor suggestions/comments. I am doing some traveling today so might not get to merging this for a day or so, btw.

2022-09-21 17:27 UTC, danielpatrickhug commented on stable_diffusion_videos/stable_diffusion_walk.py
> +    prompts:List[str] = ["blueberry spaghetti", "strawberry spaghetti"],
sure! no, I agree with those changes. thank you for bringing them up. it would be good to add a Makefile to run style checks and linters.

2022-09-21 17:27 UTC, danielpatrickhug commented on stable_diffusion_videos/stable_diffusion_walk.py
> +    assert len(prompts) == len(seeds) == len(num_steps) +1
totally agree!

2022-09-21 17:28 UTC, danielpatrickhug commented on stable_diffusion_videos/stable_diffusion_walk.py
> +    total_frame_count = sum(num_steps)
thank you.

2022-09-23 22:58 UTC, nateraw commented on stable_diffusion_videos/stable_diffusion_walk.py
> +    prompts:List[str] = ["blueberry spaghetti", "strawberry spaghetti"],
Tracking that with #54

2022-09-23 22:59 UTC, nateraw commented
@danielpatrickhug ready for review again?

2022-09-24 14:22 UTC, danielpatrickhug commented
@nateraw Hey, yes, it should be good to go.

2022-09-26 19:18 UTC, nateraw commented
cool - apologies if it takes me a few days to get this merged...will have to resolve conflict + give it a test drive and I have a few other things I'm juggling. From first glance it looks like its ready to go though :)

2022-10-03 20:58 UTC, merged